### ISSUE TITLE
I can't browse hidden (dot)folders

### ISSUE THREAD

**Issue by paweljonik** [sveale/remote-edit#100]
While showing hidden (dot)files works perfectly, I can't see dotted folders while browsing remote host.

**Comment by sveale** [comment]
Works great here.
what atom and remote-edit version are you using? Have you tried multiple hosts? ftp or ssh? os? any errors in console?

**Comment by paweljonik** [comment]
Works now for me too. I don't know if it was the recent update of the plugin or is it just me blind at the time being ;-)
