### ISSUE TITLE
Cant browse file if password is not saved in server config

### ISSUE THREAD

**Issue by vince68** [sveale/remote-edit#103]
If I dont save the password but leave the field blank, it ask me for the password to establish the connection. It say connection ok, but I cant browse the folders. If I store the password on the ftp or sftp connection I get the list of files and all works good. Did I miss something when the password field is blank or it's a bug ?

**Comment by jckz82** [comment]
I'm having the same issue on FTP connection.  When I don't set the password, I can't view the files, although it says Connection OK.

**Comment by sveale** [comment]
Patch published in remote-edit@v1.8.14. Great if you could test and confirm.

**Comment by jckz82** [comment]
BINGO WAS HIS NAMEO! 
Works for me, thanks.

**Comment by vince68** [comment]
Yep, works for me too, thank you.

2015-07-25 17:12 GMT+02:00 Sverre Aleksandersen <notifications@github.com>:

> Closed #103 <https://github.com/sveale/remote-edit/issues/103>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sveale/remote-edit/issues/103#event-365223747>.
>



--
