### ISSUE TITLE
Uncaught SyntaxError: Unexpected token t

### ISSUE THREAD

**Issue by stephenstgo** [sveale/remote-edit#108]
[Enter steps to reproduce below:]

1. Packages --> Remote Edit --> Browse Hosts

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.14

### Stack Trace

Uncaught SyntaxError: Unexpected token t

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.0.3%22%2C%22shellLoadTime%22%3A448%2C%22initialPaths%22%3A%5B%5D%7D:1

SyntaxError: Unexpected token t
    at Object.parse (native)
    at /Users/stephenstgo/.atom/packages/remote-edit/lib/model/inter-process-data-watcher.coffee:93:54
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

### Commands

```
     -0:00.7.0 remote-edit:show-open-files (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "remote-edit": {
    "rememberLastOpenDirectory": true,
    "followLinks": false,
    "foldersOnTop": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.11
linter, v1.3.0
minimap, v4.12.2
pigments, v0.9.3
remote-edit, v1.8.14
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by sveale** [comment]
Can you send me the contents of ~/.atom/remoteEdit.json? Be sure to sanitize any passwords/IPs. You can post it here or send it to me at sverre.aleksandersen (at) gmail.com.

**Comment by stephenstgo** [comment]
I sent you an email with the info

**Comment by stephenstgo** [comment]
Trying to see if there was any update on this.

**Comment by sveale** [comment]
Hi. I’ve received the email, but have been swamped lately so havent really had time to look at it.
In the meantime, I’d urge you you try and delete ~/.atom/remoteEdit.json to see if that helps.
__You’ll lose all the hosts and files you’ve added if you do this, but seeing as how it doesn’t work I’m sure thats allright.__
Alternatively, just backup the file.
Let me know if it helps.

I’ll look more into it as soon as I have time.

**Comment by stephenstgo** [comment]
Ok I will try this out to see if it helps. Besides this problem the package
works very well!

**Comment by sveale** [comment]
Hi! I've published what I hope will be a fix. Let me know if you're still experiencing issues after installing it :)
