### ISSUE TITLE
Incorrect download files with different charsets

### ISSUE THREAD

**Issue by stdex** [sveale/remote-edit#110]
1) I have file with windows-1251 charset. When I open it in notepad++ it's opened in correct charset.
2) When I try to open this file with your plugin it convert text (contains of file) to utf8 and convert charset of file to utf8. It broke text in file and I can't restore it back. (I can change charset, but it's not working, becouse your plugin convert text to utf8 too)
3) If I'm open local file with windows-1251 charset in atom.io I can change charset and text are not broken in it. Also I use plugin auto-encoding that can do it automatical.

You can see screenshot, it really problem in remote-edit, e.g. remote-ftp package work with my files correctly.

![image](https://cloud.githubusercontent.com/assets/4608879/9097151/80095b9c-3bca-11e5-9940-e05e0e36884a.png)
![image](https://cloud.githubusercontent.com/assets/4608879/9097158/8a88cd6e-3bca-11e5-98a1-e08e181ab072.png)
![image](https://cloud.githubusercontent.com/assets/4608879/9097167/9283c244-3bca-11e5-8f38-08efcba41286.png)

**Comment by sveale** [comment]
This should be fixed in the patch I just pushed, remote-edit@v1.8.15. Can you check and confirm?

**Comment by stdex** [comment]
It looks like fixed.
