### ISSUE TITLE
How to edit or remove exist host?

### ISSUE THREAD

**Issue by yojo3000** [sveale/remote-edit#116]
I want to remove some exist remote hosts but I just can't find where to do it? please help me

**Comment by sveale** [comment]
When in "Remote Edit: Browse", <kbd>Shift+d</kbd> will delete the selected host.

**Comment by dorian-marchal** [comment]
Is there a way to __edit__ an existing configuration ?

**Comment by sveale** [comment]
Shift+e

---- Dorian Marchal skrev ----

**Comment by dorian-marchal** [comment]
Thanks :+1:
