### ISSUE TITLE
Cannot go up a folder

### ISSUE THREAD

**Issue by HeroicHD** [sveale/remote-edit#120]
When I go up a folder ('..' Button), my FTP seems to disconnect.

So it goes from this:
![image](https://cloud.githubusercontent.com/assets/8153101/9439893/5c31d134-4aae-11e5-8725-cf189ed80a03.png)

To this:
![image](https://cloud.githubusercontent.com/assets/8153101/9439912/8c16c3be-4aae-11e5-9063-7351af02a5df.png)

**Comment by sveale** [comment]
What kind of FTP server is it? Have you tried any other clients?
