### ISSUE TITLE
why does show open files show multiple entries for same file?

### ISSUE THREAD

**Issue by drq883** [sveale/remote-edit#128]

**Comment by sveale** [comment]
Because if a file on a specific server could only be downloaded once, the potential for it getting out of sync with the servers version is quite large. I didn't, and don't, want to deal with that.

**Comment by sveale** [comment]
There is a settings option titled "Clear open files on start" or something like that that allows you to purge the downloaded files each time atom is opened up.

**Comment by drq883** [comment]
I do have that setting in my setup. I was just curious why there were around 10 instances of the file in the open list. It’s not a big problem.

Thanks for a great package that helps out when working from home.
