### ISSUE TITLE
Testla bundle failure

### ISSUE THREAD

**Issue by Gachl** [sveale/remote-edit#130]
Trying to install this package on Atom.io but all I get was this error message:

    > keytar@3.0.0 install C:\Users\Username\AppData\Local\Temp\2\apm-install-dir-115821-5688-1b3edmd\node_modules\remote-edit\node_modules\keytar
    > node-gyp rebuild

    C:\Users\Username\AppData\Local\Temp\2\apm-install-dir-115821-5688-1b3edmd\node_modules\remote-edit\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Users\Username\AppData\Local\atom\app-1.0.13\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

    gypnpm WARN installMany asserts.js was bundled with testla@0.1.3, but bundled package wasn't found in unpacked tree
    npm WARN installMany fn.js was bundled with testla@0.1.3, but bundled package wasn't found in unpacked tree
    npm WARN installMany observer.js was bundled with testla@0.1.3, but bundled package wasn't found in unpacked tree
    npm ERR! Windows_NT 6.2.9200
    npm ERR! argv "C:\\Users\\Username\\AppData\\Local\\atom\\app-1.0.13\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Username\\AppData\\Local\\atom\\app-1.0.13\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Username\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Username\\.atom\\.apmrc" "install" "C:\\Users\\Username\\AppData\\Local\\Temp\\2\\d-115821-5688-lg1pnq\\package.tgz" "--target=0.30.6" "--arch=ia32" "--msvs_version=2013"
    npm ERR! node v0.10.40
    npm ERR! npm  v2.13.3
    npm ERR! code ELIFECYCLE

    npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the keytar package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls keytar
    npm ERR! There is likely additional logging output above.

**Comment by fojtCz** [comment]
Did you install dependencies for node-gyp?

https://github.com/nodejs/node-gyp#installation

**Comment by Gachl** [comment]
No, I pressed the "Install" button in Atom and when it didn't work I scrolled through the description where it says nothing about dependencies.

**Comment by sveale** [comment]
I've published a patch which should resolve the issue, v1.8.21.

For future reference, the issue stems from node-keytar not compiling on win7.
