### ISSUE TITLE
Files are not displayed after successfully reading from remote server

### ISSUE THREAD

**Issue by IntegersOfK** [sveale/remote-edit#143]
As of today, when I open a file from a remote server (sftp), the green alert says that the file was read successfully (as expected). Normally Atom would then display a new tab with the file, but no new tab opens and my workspace remains blank. When I list the downloaded files with "Show open files", they're all there. Again when I click on one, Atom does not actually open or display the file in the editor window. No errors are displayed and there's nothing to suggest a problem with the fileserver.

I am using MacOS 10.10.5. I can see when I download a file that the json config file for remote edit is updated with the file's server and cache information, and the files are downloaded locally into a subdirectory in my /private folder. The files simply don't open in the editor window.

**Comment by asimshamim2015** [comment]
I am also experiencing this issue! It will read the remote file, however it won't load.

**Comment by rekikn** [comment]
Im can't see the files too. Clean reinstall of Atom don't fix error :/

**Comment by westonkd** [comment]
Same

**Comment by boscolau** [comment]
Issue occurs after upgraded to Atom 1.2.0
Reinstalled Atom 1.1 the problem was gone, but Atom would auto update to 1.2.0.
Cannot disable autoupdate, so this is still a problem

**Comment by asimshamim2015** [comment]
I've temporarily fixed this issue.

- Find your release issue [here](https://github.com/atom/atom/releases/tag/v1.1.0), and download. 
-Extract the package and delete the Update file. On Windows, that file is **Update.exe**. From there just open Atom normally. By downgrading to 1.1.0, my remote-edit is working again. 

Hope this helps

**Comment by adriangordon1231** [comment]
I am having this issue as well.

**Comment by fburleigh** [comment]
Same in Atom 1.3 beta:

`Uncaught (in promise) Error: Must pass a config parameter when constructing TextEditors`

**Comment by mattcrox** [comment]
Same issue for me...

**Comment by nobutsta** [comment]
Also not work on Atom 1.2.3, uninstalled already.

**Comment by rabgc** [comment]
I experience this issue also.

**Comment by basilfawlty** [comment]
Same issue here. Is this going to be fixed?

**Comment by drq883** [comment]
There is a pull request for a patch to fix this by user tk3369

https://github.com/sveale/remote-edit/pull/152

**Comment by sveale** [comment]
Published mike's PR #146 that should fix the issue., see remote-edit@v1.8.23.

**Comment by drq883** [comment]
Thanks. I've missed it. 

- David (from iDevice)

**Comment by drq883** [comment]
How long does it normally take for Atom Available Updates to see newly built packages?

**Comment by sveale** [comment]
Usually instant. Do you have the newest atom version? 

---- David Quattlebaum skrev ----

**Comment by drq883** [comment]
1.2.1

It’s downloading an update now (over my parent’s SLOW network).

**Comment by sveale** [comment]
That's probably the reason. The fix is only for 1.2.3+ I think. 

---- David Quattlebaum skrev ----

**Comment by drq883** [comment]
Updated Atom to 1.2.4, remote-edit to 1.8.23. I'm now back in business.

Thanks @sveale and @mike-kfed for fixing this.

**Comment by IntegersOfK** [comment]
Confirmed fixed! I am happy we got to the bottom of this, thanks guys.
