### ISSUE TITLE
Can not add new host

### ISSUE THREAD

**Issue by andoro** [sveale/remote-edit#147]
Dear Developer!

I've installed your package, but can't add new host.
After I'm typing the host name, it freezes and can not edit other info such as username, password etc.
My atom version is 1.2

**Comment by markusdanek** [comment]
Please provide more informations.

* What OS are you using? 
* Does it happen if you add a new sftp host, ftp host or both?
* Did you reinstalled Atom with all packages? 
* What other packages are you using?
* Do you get any error messages or similar when Atom freezes? 

Cheers

**Comment by andoro** [comment]
Here are the answers in order:
 - OSX El Capitan 10.11.1
 - It happens both, the focus is lost when I try to press TAB key, or click to another input (after that I can write to my currently opened file, but the new ftp/sftp window can be closed only with ESC key)
 - Why should I reinstall Atom with all my packages? It's a fresh install, I've updated it to 1.2.1. Also all of my packages are updated.
 - My packages are attached.
 - No, I told you wrong. Atom not freezes, only your window. No error messages at all.

<img width="820" alt="01" src="https://cloud.githubusercontent.com/assets/775765/11252533/fc9cee80-8e36-11e5-9752-fe8eadbc0c8c.png">
<img width="804" alt="02" src="https://cloud.githubusercontent.com/assets/775765/11252534/fccc6af2-8e36-11e5-9493-9c42673e4c5e.png">
<img width="806" alt="03" src="https://cloud.githubusercontent.com/assets/775765/11252535/fccef6dc-8e36-11e5-8996-0258bebee8f4.png">

**Comment by andoro** [comment]
OK I know what the hell happens. I'm using native-ui theme and this is the problem.
