### ISSUE TITLE
File doesn't open after "Successfully read remote file"

### ISSUE THREAD

**Issue by tvance989** [sveale/remote-edit#148]
I can view my remote directory fine in the remote-edit file browser. When I select a file to open, I get the usual display messages--including "success"--but the file isn't opened after that. I've tried with multiple remote servers, directories, and files. I see no error messages. Is there a log or something I can paste to help someone dig into this? Is anyone else having this problem?

![atom](https://cloud.githubusercontent.com/assets/4656050/11272264/34d30ab4-8e91-11e5-9981-4e00e7dc0f73.png)

**Comment by theclapp** [comment]
Same here.  (Same problem as #143, by the way.)  Installed Atom just this morning to use exactly this package, and it's broken.  ::great sadness::

**Comment by tvance989** [comment]
Thanks for the link @theclapp and sorry for the repost!
