### ISSUE TITLE
Remote edit does not open file

### ISSUE THREAD

**Issue by rabgc** [sveale/remote-edit#150]
It appears that a connection is made to the remote server and I can navigate directories there, but when I select a file it does not appear in the Atom browser for editing.  I am using remote-edit 1.8.22 with Atom 1.2.3 on Mac with El Capitan 10.11.1

**Comment by markusdanek** [comment]
See "Files are not displayed after successfully reading from remote server #143"

**Comment by sveale** [comment]
Published mike's PR #146 that should fix the issue., see remote-edit@v1.8.23.
