### ISSUE TITLE
Atom Remote Edit no longer displaying open files

### ISSUE THREAD

**Issue by marcbolh** [sveale/remote-edit#151]
I have been using Remote Edit package for a while without incident. Suddenly, I'm unable to view open files from server. I verified that opening local file works fine.

When I try to open a file from the server, dialogue goes through to completion "Successfully read remote file", just doesn't show it in the editor. I verified that the remote files aren't empty.

I installed latest version of atom v1.2.4 and uninstalled / reinstalled remote edit v1.8.22 but to no avail.

Any ideas?

**Comment by markusdanek** [comment]
See "Files are not displayed after successfully reading from remote server #143"

**Comment by tk3369** [comment]
Looks like a recent Atom code change broke this.

Error:
<img width="946" alt="screen shot 2015-11-26 at 3 59 11 pm" src="https://cloud.githubusercontent.com/assets/1159782/11431895/c05bd55a-9456-11e5-8966-9d7c525524b3.png">

Atom blame history
https://github.com/atom/atom/blame/master/src/text-editor.coffee
<img width="927" alt="screen shot 2015-11-26 at 4 00 24 pm" src="https://cloud.githubusercontent.com/assets/1159782/11431901/e3fe3d4a-9456-11e5-85d1-28763cc330da.png">

**Comment by tk3369** [comment]
I fixed it and submitted a pull request https://github.com/sveale/remote-edit/pull/152

**Comment by marcbolh** [comment]
Good news, waiting for update... ftp'ing files back & forth while waiting 😶🔫

**Comment by amitgit07** [comment]
I am new to Atom and remote-edit too, I show that there are 3 files that are open through sftp, but dont know where to see these files. How can i edit this file so that it is synced with server.

**Comment by opensource-yl** [comment]
Yeah, how to edit my files after connecting..

**Comment by sveale** [comment]
Published mike's PR #146 that should fix the issue., see remote-edit@v1.8.23.
