### ISSUE TITLE
sudo mode

### ISSUE THREAD

**Issue by UltimatePancake** [sveale/remote-edit#157]
Any way to have a "sudo" mode to save files with read-only access? (Would only work when the user is in the sudoers file anyway)

**Comment by sveale** [comment]
This is not supported by the package. The underlying library used for ssh connections, [ssh2](https://github.com/mscdex/ssh2), seems to support this in _exec_ mode, but remote-edit uses the sftp functionality. Unfortunately I do not have the opportunity to add it, but you're more than welcome to submit a PR.
