### ISSUE TITLE
How to edit existing host ?

### ISSUE THREAD

**Issue by omixk** [sveale/remote-edit#158]
or delete previous host?

**Comment by sveale** [comment]
Read the readme.

**Comment by omixk** [comment]
how can you edit the previous one when you create a new one .

**Comment by omixk** [comment]
https://camo.githubusercontent.com/8d748532e05799af41c671c214af7e7b38a6fd58/687474703a2f2f696d6775722e636f6d2f476758683571512e706e67

this is the picture of edit host  in ready

**Comment by omixk** [comment]
use shift + e

**Comment by sveale** [comment]
Look at the section that talks about keyboard shortcuts, not the pictures. 

---- oMiXk skrev ----

**Comment by omixk** [comment]
hi, I think add some text to the picture will be helpful
https://www.dropbox.com/s/s65mxi2y943i7rp/Untitled.png?dl=0
