### ISSUE TITLE
Hidden files (.htaccess etc)

### ISSUE THREAD

**Issue by xd0** [sveale/remote-edit#164]
Hi,

I've got a problem listing hidden files. Should I able to list hidden files through FTP with this extension? What could be the problem that i can't see hidden files?

As you can see in attached screenshots, if I browse through FileZilla i see .htaccess but not with remote-ftp via Atom.

![ftp](https://cloud.githubusercontent.com/assets/5164069/12481777/b6ea8e96-c04b-11e5-880b-6b0c72599d91.png)
![remote-edit](https://cloud.githubusercontent.com/assets/5164069/12481778/b6ec3ade-c04b-11e5-8c38-4f3fc986a634.png)

**Comment by sveale** [comment]
There is an option, "Show hidden files", that enables display of hidden files. Should be in the package settings :)

**Comment by xd0** [comment]
Thanks for your answer!
Even if I tick that box i can't see any hidden files (in this case .htaccess files). Could it be a bug?
