### ISSUE TITLE
Feature request: Enable support for AWS S3

### ISSUE THREAD

**Issue by davidafuller01** [sveale/remote-edit#168]

**Comment by sveale** [comment]
Please provide more details.

**Comment by davidafuller01** [comment]
remote-edit allows an Atom user to browse and edit remote files using FTP and SFTP.  Unless I've missed it in the documentation, remote-edit does not allow a user to do the same for files hosted in AWS S3 over HTTP via the Amazon S3 REST API.  As a result, one has to use the AWS web interface or a specialty tool like [Transmit](https://panic.com/transmit/) to move files back and forth between remote AWS S3 buckets and local systems to facilitate file editing.  remote-edit incorporating the capability to access AWS S3 would be a very useful thing.
