### ISSUE TITLE
Question: skipping the host selection

### ISSUE THREAD

**Issue by philippe99** [sveale/remote-edit#171]
Hi.
I daily use remote-edit to edit files on a unique remote Unix machine.
Most of the time, during several days, I have to edit files from a same remote directory.

Up to now - or do I misss something- I recall remote-edit in the palette, select the host from the list (the list contains all the target directory on the unique host I have deal with during the month) and then select the file to open.

Is there a way to skip the host selection -aka always open the same destination from the list- to go directly to the browse of remote files ?

Thx

**Comment by sveale** [comment]
If you have enabled the "Remember last open directory" in the settings panel it will automatically take you to the same directory for said host that you were in last time. You still have to do the host selection. Alternatively, if you want to edit the same file, you can use "Show open files".
