### ISSUE TITLE
Leaving remote file open hangs Atom the next time its opened

### ISSUE THREAD

**Issue by marius311** [sveale/remote-edit#181]
Using Atom 1.7.3, remote-edit 1.8.24 on Ubuntu 16.04. 

To reproduce:
* Open Atom
* Open some remote file using remote-edit
* Close Atom, but don't close the file first
* Reopen Atom

At this point I just get a blank screen and an "hourglass" cursor. I can close Atom, the next time I reopen it is opens correctly (although the remote file is gone).

**Comment by stemd** [comment]
Probably just duplicate of #169

Please check, so we wouldn't have duplicate issues.

**Comment by marius311** [comment]
Ah, missed that thanks, I'm definitely referring to the same thing. I'll close this issue.
