### ISSUE TITLE
When browsing remember last directory used.

### ISSUE THREAD

**Issue by arleslie** [sveale/remote-edit#193]
When you use `Remote Edit: Browse` and select a host it brings you to the default directory.
It would be nice to remember the last past that was used instead of having to go navigate back to the path just to open a file in the same folder you were just in.

**Comment by dannymulvihill** [comment]
There is a `remember last directory` check box in the settings for remote-edit package. Open settings, go to packages, select remote edit and scroll down a bit to find.
