### ISSUE TITLE
Autocomplete doesn't work with files opened on a server via SFTP

### ISSUE THREAD

**Issue by GalacticSun** [sveale/remote-edit#196]
I'm editing files on a server via SFTP (using Remote Edit), and the default Atom autocomplete won't work with these files. The little popup just never comes up for me when editing remote files.  I can't figure out how to enable it.  Is this a bug with this package?  Otherwise it's great.

**Comment by martinfojtik** [comment]
this bug is fixed in Atom 1.10 https://github.com/atom/atom/tree/v1.10.0

**Comment by GalacticSun** [comment]
Awesome!  Thanks.
