### ISSUE TITLE
Can't see any hosts on the Windows client

### ISSUE THREAD

**Issue by mostlyvirtual** [sveale/remote-edit#241]
So I added a couple of hosts, but they don't show up. Instead I just get the loading icon:
http://puu.sh/zkbzH/a732de43eb.png

**Comment by erwinagpasa** [comment]
me too

**Comment by jediller** [comment]
I appear to have the same problem as well

**Comment by borgesa** [comment]
I am also having the same problem.

Remote edit 1.9.0
Atom 1.28.2
Windows 10

Only action I do: 'Ctrl + A + B' + Enter...

Installed Atom packages:
busy-signal (1.4.3)
intentions (1.1.5)
linter (2.2.0)
linter-pylint (2.1.1)
linter-ui-default (1.7.1)
(and remote edit)

Help with this would be greatly appreciated!
