### ISSUE TITLE
support PuTTY Pageant as SSH Agent (use Plink)

### ISSUE THREAD

**Issue by fnkr** [sveale/remote-edit#44]
Use Plink instead of OpenSSH on Windows so the user can use PuTTY Pageant for authentication. Pageant is probably the most used SSH Agent on Windows.

http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html

**Comment by sveale** [comment]
Pageant is now default SSH agent on windows, ref. commit 8b7a676b8d9075b598439a273da9ec016cdbe330.
Added settings option to override default agent (pageant on win32, socket on *nix).
