### ISSUE TITLE
issues using agent and key

### ISSUE THREAD

**Issue by opennomad** [sveale/remote-edit#50]
Running atom 0.152.0 and remote-edit 1.6.0 on Ubuntu 14.04 I can't seem to connect using the agent or key choices. Password works.

I did some investigation and the error always is 'Timed out while waiting for handshake' around line 232. The value of `self._state` seems to always be "initexchg". I also dumped the `opts.agent` and it points to the right socket for the SSH agent. I also tried adding the "initexchg" to the conditional, but then it just sits there (yeah, stupid heavy handed approach).

Using the agent with the normal openssh cli tools works as expected and so do a couple of GUI tools I tried.

**Comment by sveale** [comment]
Are you still experiencing this issue? I just tried key and agent auth on a fresh install of debian testing and it worked great.

**Comment by opennomad** [comment]
yeah, I just tried 1.6.2 as well and I continue to see the timeout error

**Comment by opennomad** [comment]
I just tried again using 0.177.0 and I'm still seeing the handshake error. I moved my entire `.atom` dir out of the way and then installed just remote-edit. Then I got the following strack trace:

```
TypeError: undefined is not a function
  at /home/matthias/.atom/packages/remote-edit/node_modules/ssh2/lib/client.js:136:12
```

It's smelling like something about my SSH is not working ...

**Comment by opennomad** [comment]
I found [this bug](https://github.com/mscdex/ssh2/issues/142) which might be related.
