### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by JiriMacha** [sveale/remote-edit#51]
Uncaught SyntaxError: Unexpected end of input

Atom Version: 0.153.0
System: linux 3.13.0-43-generic
Thrown From: remote-edit package

This error occurred during deleting (shift d) of "opened files".
Moved from atom list of issues.

**Comment by sveale** [comment]
Have you experienced this issue more than once? How many items were left in the list when this occured? Did you delete from the top or bottom?
