### ISSUE TITLE
Updating host information

### ISSUE THREAD

**Issue by JamesGould123** [sveale/remote-edit#52]
There appears to be no internal way to change the username/password/IP or to delete saved hosts. I can implement this functionality in the next several days/weeks, unless this functionality already exists and I somehow missed it.

Also worth noting that it is currently showing no files on my server, but it seems likely that that is a problem with my server.

**Comment by sveale** [comment]
Hi. You should be able to edit hosts from the browse hosts menu with shift-e. In regards to no files being displayed, it would be great if you could double check where the problem lies. Let me know if aforementioned doesn't work :-)

**Comment by sveale** [comment]
Oh, and shift-d deletes em from same context.

**Comment by JamesGould123** [comment]
Well that's embarrassing that I missed that.

I've figured out what was wrong with my server configuration, it's working fine now.
