### ISSUE TITLE
ENOENT when opening existing files

### ISSUE THREAD

**Issue by arcanis** [sveale/remote-edit#54]
I'm not sure why, but when I select a file (after being connected), it tells me that I can't because ENOENT (which is supposed to mean that the file doesn't exists, I guess).

**Comment by sveale** [comment]
Can you edit the file with the same credentials using another editor or via putty/ssh?

---- Maël Nison skrev ----

**Comment by arcanis** [comment]
Yep. My usual workflow is putty -> emacs, and it works fine. It also works when using ExpanDrive to map the directory to a Windows net drive (still with the same credentials).

**Comment by malko42** [comment]
Same issue, ftp protocol works though.

**Comment by AlainBarthelemy** [comment]
same issue

**Comment by sveale** [comment]
Related to https://github.com/mscdex/ssh2/issues/225.

Likely occured after ssh2 upgrade from 0.3.x to 0.4.x.

**Comment by sveale** [comment]
Pushed new version (1.6.4) that species that version 0.3.6 of ssh2 should be used. Temporary until mscdex/ssh2#225 is fixed or proper workaround is found.
