### ISSUE TITLE
Editing still uses old config

### ISSUE THREAD

**Issue by reggi** [sveale/remote-edit#63]
If you edit a host in config it will still use old host.

**Comment by sveale** [comment]
I've published a new version of remote-edit that solves an issue where manually editing the config file did not result in changes in Atom. Great if you could check it out and let me know if it solves your issue.

**Comment by reggi** [comment]
Hey @sveale I'm not gonna get a chance to test it till later in the week. I'll get back to this issue once I do.

**Comment by alanhouser** [comment]
I wanted to try this, but not sure where to find remote-edit's config.

**Comment by sveale** [comment]
~/.atom/remoteEdit.json

**Comment by sveale** [comment]
@reggi have you gotten around to testing this? :-)

**Comment by reggi** [comment]
I'm trying to save new settings and nothings happening at all. I hit save, the dialogue closes and settings aren't saved to `~/.atom/remoteEdit.json`.

Sadly I'm not working with any FTP connections at the moment so I don't have any creds handy.

**Comment by sveale** [comment]
Should be fixed in commit 802e11bc4a4cc50556910363b641bfe99e6765aa
