### ISSUE TITLE
create new file

### ISSUE THREAD

**Issue by huglester** [sveale/remote-edit#64]
Hello,

is there a way to create a new file using this package?

Thanks

**Comment by sveale** [comment]
Hi. 
Unfortunately this isn't possible. 
It is fully possible to implement, but I think it would be awkward unless the select-list were replaced by a file-tree (ref. issue #25).

**Comment by mosbth** [comment]
The ssh/sftp-plugin in SublimeText 2 has the same dropdown menu that you have, it contains a menu-item for file creation. It works nicely, without the need of a complete file-tree. 

Just a thought, but such a feature is still not-high-prio in my mind.

**Comment by sveale** [comment]
Thanks hadn't thought about that. It's definitively the easier way to to it. I'm only using the package to do quick edits so this won't be a priority for me to implement, but I'd be happy to accept a PR .
