### ISSUE TITLE
Delete old configs, add some more functionality

### ISSUE THREAD

**Issue by visualcookie** [sveale/remote-edit#65]
Hi,

first to say: great tool, after Remote-Sync isn't updated. Now to my request(s) or issue(s) I'm having right now.

1. Couldn't find any functionality for deleting old configs.
2. I would appreciate if I could configure if upload on save is on for that config or off. At the moment it's only possible in the package settings itself.
3. An edit functionality for existing configs would be a must.
4. Just discovered that I also can't upload files using tree view > right click on file

If there were already some of the requests I got, just ignore them. Would love to gain some feedback, what you think 'bout it and if it's already on plan for feature updates.

Until then: Have a nice day. :v:

**Comment by sveale** [comment]
Hi. Thanks :)

What do you mean by config? Are you referring to all added SSH servers and corresponding files, or do you mean the individual servers?

**Comment by visualcookie** [comment]
Hi @sveale,

the servers I add with this package. If it has old login credentials I would like to change it or if I don't need this server anymore, remove it from the servers view.

**Comment by sveale** [comment]
Look at the readme :-) 

---- Dean Hidri skrev ----

**Comment by visualcookie** [comment]
Dang, how could I missed that? :laughing: 

Thanks. :+1:
