### ISSUE TITLE
Malformed cygwin unix socket file on Windows 7

### ISSUE THREAD

**Issue by digihash** [sveale/remote-edit#66]
Hi

I installed remote-edit in atom on my windows 7 x64 system. I configured the SSH agent setting to be "c:\Program Files Portable\Putty\putty.exe.

I added a server, which I can connect to with the correct user and on port 22 with password authentication. But when I try to connect, I get the error message: "Malformed cygwin Unix socket file".

I don't have cygwin installed.

Do you know what the problem could be here?

Regards
Digihash

**Comment by sveale** [comment]
Hello,

putty.exe is not an SSH agent. 
You should use pageant which, which I think is created by the people behind putty.

By default, remote-edit on windows uses pageant. You need to remove the file path you entered, and leave it blank or enter "pageant".
Chekc out (this link)[http://the.earth.li/~sgtatham/putty/0.58/htmldoc/Chapter9.html]) for how to use pageant.
