### ISSUE TITLE
Size: null, Ntime: null, Permissions: null

### ISSUE THREAD

**Issue by alanhouser** [sveale/remote-edit#67]
I've gone through all steps and settings, and cannot seem to push a file to the Squarespace server. 
Directory info is being read apparently (last update via Espresso2). Hrmm

I'm really loving this package so far, but making it work is obviously important. HAHA
Guess I'll try "sftp deployment" again for a day. 

![null-null-null](https://cloud.githubusercontent.com/assets/4256989/6724450/a977a44e-cdce-11e4-8c8c-94ed76a4ee95.png)

**Comment by sveale** [comment]
Have you opened the file from the server? It's not possible to create new files on the server using this plugin.

**Comment by alanhouser** [comment]
No, I didn't, but in the previous hours I was also trying to get "sftp deployment" to work. Maybe 'empty' folders were created and sent-up? Seems so weird.

**Comment by sveale** [comment]
Have you done anything else with this? I don't really understand why you're having problems.

**Comment by alanhouser** [comment]
Thanks for your patience @sveale. I'm going to give it another go with Atom 1.0 now and I'll report-back.

**Comment by alanhouser** [comment]
@sveale same exact issue. New Project and new path on server. 
— When going to PACKAGES menu / REMOTE EDIT / BROWSE HOSTS - cannot view files; all I get is this error. 

![null](https://cloud.githubusercontent.com/assets/4256989/8441973/c1e320f4-1f49-11e5-93e2-76e98069cc6d.png)

**Comment by sveale** [comment]
So the issue is that you cannot view files that are located on the existing server? What if you try to choose one of the directories in the above screenshot?
