### ISSUE TITLE
Open file, default directory is same as last file saved

### ISSUE THREAD

**Issue by mosbth** [sveale/remote-edit#68]
Feature-suggestion.

I come from SublimeText 2 with the ssh/sft-plugin they have. I usually have en entry-point to my host and thereafter I move to different directories until I find the file I want to edit. 

Then, quite often, I want to edit another file in the same directory.

In remote-edit I need to restart from my entry-point and navigate to the directory. But the plugin in ST2 had another shortcut key that opened up "current directory", being the directory of the last saved remote file.

It saved me som time and hassle and makes it easier to edit several files relative the current directory.

A "workaround" is to have several entry points (hosts with directory path), but I learned to like the feature of opening up a new file relative last saved file with just one key combination.

The key combination could be `ctrl` `cmd` `n`, same-ish as in ST2, sftp-plugin.

**Comment by sveale** [comment]
Sounds like a smart way to do it. I must agree it's a bit of a hassle to re-navigate each time if you're editing multiple files. I'll add it to the todo list, unless you're interested in trying to implement it yourself?

**Comment by mosbth** [comment]
It would be a nice challenge,  but I'll pass for now. Lets see if anybody else picks it up.

**Comment by sveale** [comment]
Added in PR #74
