### ISSUE TITLE
Remote Edit doesn't follow symlinks

### ISSUE THREAD

**Issue by horvan** [sveale/remote-edit#70]
I have tried to user remote Edit on Widows and connected it successfully to a proftpd server. I've entered my home path just because I am lazy as every good coder should be and tried to follow a symlink to my public_html folder. remote edit has told me that <b>this is not a regular file</b> 

Now we could start a discussion about how to handle a symlink file. Open the file to edit or follow the symlink as evry good editor will do. In my person I prefer the second option. But I'd like to mention that remote edit currently doesn't handle symlinks either the one way nor the other. 

Take you time. Have a look in to it and of coures a nice day.

**Comment by sveale** [comment]
I've added initial support for symlinks. Haven't gotton around to figuring out how to determine if the symlink points to a file or directory. Would be great if you could try it out and give me some feedback before I publish an updated version :)
