### ISSUE TITLE
Allow editing of "hidden" files (starting with '.')

### ISSUE THREAD

**Issue by pnosko** [sveale/remote-edit#73]
Hidden files are not listed in directory contents, and won't be opened even if you type the file name to the filter box.

**Comment by sveale** [comment]
Toggleable in settings. 

---- pnosko skrev ----

**Comment by pnosko** [comment]
Oh, sorry, I didn't see that. Is there a reason it's not turned on by default?

**Comment by sveale** [comment]
No worries. Well, that's essentially the default setting for all file managers, so I guess that were a contributing factor. It's configurable so it doesn't really matter. 

---- pnosko skrev ----
