### ISSUE TITLE
FWIW: Pop-up messages ruin my workflow

### ISSUE THREAD

**Issue by mark-hahn** [sveale/remote-edit#75]
I don't want to stop and watch pop-ups when working.  I'd like to continue without a break in my concentration.  I liked the old notifications much better.  Maybe this complaint belongs in the atom/atom repo because I hate the notifications everywhere they are used.

**Comment by sveale** [comment]
Yeah I was afraid it would be too invasive.
What do you think about having this as an option? Ie. let the user choose
atom-notifications or atom-message-panel in settings.

**Comment by mark-hahn** [comment]
I think I have a fix for the whole editor.  See my recent post at https://discuss.atom.io/t/can-i-turn-off-the-notifications/17117/16.

**Comment by mark-hahn** [comment]
@benogle says they are adding the icon and count to the status bar.  So I'm happy.
