### ISSUE TITLE
After last update im unable to create new host and connect to them

### ISSUE THREAD

**Issue by goseeped** [sveale/remote-edit#81]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-edit](git://github.com/sveale/remote-edit) package, v1.8.2

### Stack Trace

Uncaught SyntaxError: Unexpected string

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.0%22%2C%22initialPaths%22%3A%5B%5D%7D:1

SyntaxError: Unexpected string
    at Object.parse (native)
    at /Users/Gosmac/.atom/packages/remote-edit/lib/model/inter-process-data-watcher.coffee:93:54
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

### Commands

```
     -0:01.1.0 remote-edit:new-host-sftp (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "vim-mode"
    ]
  },
  "remote-edit": {}
}
```

### Installed Packages

```coffee
# User
copy-on-select, v0.2.0
minimap, v4.10.0
remote-edit, v1.8.2

# Dev
No dev packages
```
regards

**Comment by sveale** [comment]
Can you still connect to old hosts? Have you tried reinstalling the package?
What kind of host are you trying to connect to?

**Comment by goseeped** [comment]
Hi thanks for the reply , Initially i have connected to a linux/ubuntu box then i receive a display that new version of remote-edit  is released after the update i try add a new linux server then i receive this error, By error i delete the old host i previously have , then i try to add it back again not luck , Yes already uninstall close atom and etc no success now i can't use the package at all :-( i was very happy with it.

**Comment by sveale** [comment]
I'm sorry to hear that. Can you try to delete the remote edit settings file? It should be located in ~/.atom/remoteEdit.json. Might be that it's become corrupted in some way. Let me know if it helps. 

---- goseeped skrev ----

**Comment by goseeped** [comment]
Hey that work, after delete the json file it work many thanks, congratulation for the module. have a good day.
