### ISSUE TITLE
When i try to connect to my VPS server , i get error: no such file.

### ISSUE THREAD

**Issue by tuberiumf** [sveale/remote-edit#86]
First i added my VPS server to server browser, and go to connect, atom connecting, loading, and i get error :( What i do wrong?
P.S:Sorry for my broken english
P.P.S: I used SFTP

**Comment by tuberiumf** [comment]
Hm... ok i enabled FTP on my server and connect with FTP

**Comment by sveale** [comment]
What error did you get?
