### ISSUE TITLE
File showing as blank... corrupted cache?

### ISSUE THREAD

**Issue by acicali** [sveale/remote-edit#88]
I just opened a file using remote-edit and was surprised to find it blank. SSHing into the server and opening the file confirmed that indeed it was not blank. Closing and opening it in remote-edit several times was not effective. Only after I ran "touch app.js" on the server did remote-edit display the file contents upon opening.

I assume this has something to do with a local cache, but I don't have any way of providing a test case or any additional information. I've only been using remote-edit for a few days, but this is the first time it has happened.  Upgraded to 1.8.4 yesterday.

Thanks for your hard work on this most excellent package!

**Comment by jmrobles** [comment]
+1

**Comment by sveale** [comment]
This should be resolved by commit ca84c45ce13864ae7de4733fabfb35ddcfde261c.
Let me know if it occurs anyway.
