### ISSUE TITLE
Shift+d does not actually delete a server from the list

### ISSUE THREAD

**Issue by lgrn** [sveale/remote-edit#90]
How to reproduce:

- Press Ctrl+Alt+b to bring up the list.
- Press Shift+d to delete the marked server.
- Press Ctrl+Alt+b to bring up the list again. Notice that the server is still there.
- Connect to the server and verify it still works.
- Press Ctrl+Alt+b again, the server is still there.

Instead of pressing Ctrl+Alt+b in step one, I've also seen the issue when pressing ESC and bringing it back up. It seems Shift+d doesn't work as expected, I would expect any server marked when pressing Shift+d to be gone forever.

Also, is there a file where this is stored so it can be edited manually?

**Comment by sveale** [comment]
All information is stored in ~/.atom/remoteEdit.json.

You're correct in assuming that the server which is marked when pressing shift-d should be removed and be gone forever. 

I've added some changes that should resolve the issue (see commit 261516e7638ba67174cdadb427446035615b8aa9).
Can you try the new version (1.8.8) and let me know if it resolves your issues?

**Comment by sveale** [comment]
It should be working now. Can you update and let me know?

**Comment by lgrn** [comment]
Confirmed that the above is no longer reproducable, cheers.
