### ISSUE TITLE
Not working in Atom 1.0.2

### ISSUE THREAD

**Issue by moezsayani** [sveale/remote-edit#92]
Keeps throwing an error in Atom 1.0.2

[Enter steps to reproduce below:]

1. ... press control+command+B
2. ... fail

**Atom Version**: 1.0.2
**System**: Mac OS X 10.11
**Thrown From**: [remote-edit](git://github.com/sveale/remote-edit) package, v1.8.10

### Stack Trace

Uncaught SyntaxError: Unexpected token \

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.2%22%2C%22initialPaths%22%3A%5B%22atom%3A%2F%2Fconfig%22%5D%7D:1

SyntaxError: Unexpected token \
  at Object.parse (native)
  at /Users/moezjanmohammad/.atom/packages/remote-edit/lib/model/inter-process-data-watcher.coffee:68:52
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```

### Commands

```
     -0:16.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 remote-edit:browse (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "remote-edit": {
    "rememberLastOpenDirectory": true,
    "foldersOnTop": true,
    "notifications": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.8.6
autocomplete-python, v0.5.1
minimap, v4.11.0
remote-edit, v1.8.10
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by sveale** [comment]
I suspect the config file for remote-edit have been corrupted in some way.

The easiest way to test this is to close Atom and then rename ~/.atom/remoteEdit.json to something else. When you start up Atom a new config file will automatically be created. Can you give that a go and see if it works?

**Comment by moezsayani** [comment]
That fixed it!

Moez

From: Sverre Aleksandersen
Reply-To: sveale/remote-edit
Date: Thursday, July 9, 2015 at 4:40 PM
To: sveale/remote-edit
Cc: "Janmohammad, Moez"
Subject: Re: [remote-edit] Not working in Atom 1.0.2 (#92)


I suspect the config file for remote-edit have been corrupted in some way.

The easiest way to test this is to close Atom and then rename ~/.atom/remoteEdit.json to something else. When you start up Atom a new config file will automatically be created. Can you give that a go and see if it works?
