### ISSUE TITLE
Password form

### ISSUE THREAD

**Issue by jkw** [sveale/remote-edit#93]
Would it be possible to make it not show passwords while typing them?

**Comment by sveale** [comment]
Related to #45 .

When I first added the prompt-for-password stuff no constructs were available in Atom to not show passwords while typing them in, and I didn't bother to build it.

I think https://atom.io/packages/nuclide-remote-projects have added this functionality. 
If you (or anybody else for that matter) would be interested in trying to implement or port the functionality from the aforementioned package I'd gladly accept a PR, but it's not something I'm going to focus on.
