### ISSUE TITLE
Issues reporting fails for Safari as default browser

### ISSUE THREAD

**Issue by michaelaye** [sveale/remote-edit#95]
As Safari does not accept git:// urls the link to auto-reporting issue link and link to the repo fail for me.

Safari version: 8.0.5
Atom: 1.0.2

**Comment by sveale** [comment]
I'm sorry but I don't quite understand what the issue with the remote-edit package is here?

**Comment by michaelaye** [comment]
In attached image from the settings view, a click on the links to sveale/remote-edit (in blue) and the "Report Issue" button fail, while these work for all other packages I have installed.

<img width="504" alt="screenshot 2015-07-14 16 17 44" src="https://cloud.githubusercontent.com/assets/69774/8686474/ef12cbc4-2a43-11e5-96b6-be39e95e049f.png">

I'm getting this error:

<img width="700" alt="screenshot 2015-07-14 16 19 23" src="https://cloud.githubusercontent.com/assets/69774/8686492/1db5e42a-2a44-11e5-9a7b-21c3daece5f0.png">

**Comment by sveale** [comment]
Fixed by commit 8088e77eda91c678d036df54d565100e19e2b683, published in remote-edit@v1.8.11.
