### ISSUE TITLE
save error: Cannot find module './dialog'

### ISSUE THREAD

**Issue by mark-hahn** [sveale/remote-edit#97]
Since the latest upgrade I can't save any files.  I get the error `Cannot find module './dialog'` in the console log.  For some reason I don't get the atom error popup and there is nothing to indicate where the error really comes from.

ubuntu 14.0.4
v 1.8.12
atom 1.0.2

**Comment by sveale** [comment]
I don't see a reason in the latest commits as to why that would happen. 
As far as I know, the dialog class or its usage haven't been changed in a while.

Did you get a stacktrace or any other info in the console?
I hate to ask, but have you tried reinstalling the package?

**Comment by mark-hahn** [comment]
> Did you get a stacktrace or any other info in the console?

No.  It looks like this and nothing can be expanded ...

[image: Inline image 1]

> I hate to ask, but have you tried reinstalling the package?

Yes.

**Comment by sveale** [comment]
I've just published v1.8.13 that should fix the issue.
Can you try it out and let me know?

**Comment by mark-hahn** [comment]
Save works now.

BTW, Is the dialog asking if you want to upload new?  Can I turn it off?  I
hit ctrl-s constantly (old muscle memory).

**Comment by sveale** [comment]
Actually, after I published the change, I discovered that the Dialog class isn't actually used there (atom.confirm is). It's been there for a long while (> several months).

You can go to the settings page and check "Upload on save". When enabled this automatically pushes changes to remote. If it is disabled, you'll be queried each time you hit ctrl-s.
