### ISSUE TITLE
Visual indicator of remote file

### ISSUE THREAD

**Issue by scaba** [sveale/remote-edit#98]
I would like to see any remote files I'm editing be somehow visibly marked to stand out from the rest of my project. My use case is I normally am working on a local copy of our repository, but sometimes I want to make quick edits on the server's copy of the file to test changes that can only tested remotely without littering the commit logs with a million little commits and I want that remote file to stand out from the rest of the opened tabs.

**Comment by sveale** [comment]
This is already present:
![screen shot 2015-07-17 at 14 46 26](https://cloud.githubusercontent.com/assets/1172163/8747436/5d6b7de0-2c93-11e5-9b59-4b1452d5bbde.png)

As you can see the remote file gets a globe icon to make it stand out.
This behavior is, unfortunately, overriden by certain other packages (file-icons being the major with over >190000 downloads).

I haven't quite figured out how to make it work if file-icons is installed.
